### ISSUE TITLE
Cargo / Vehicles loaded onto vehicles may explode due to collisions.

### ISSUE THREAD

**Issue by uaon** [7Cav/Liberation#12]
### Basic Information
**Mission version:**
0.96.7a-7cav-0.1
**Map used:**
Altis
**Server:**
Tactical Realism 2
**Time of Occurance:**
25 APR 2021 - 0000z

### Short Issue Description
When Cargo or a Vehicle is loaded onto a transport airframe, (CH53, CH47) There is a chance that desync may cause the object(s) to collide with the vehicle causing it to explode.

Reports suggest that this is most likely with the CH53, with mixed results with the C130J and CH47.

### Expected Behaviour
Vehicles shouldn't explode because of contents within vehicle.

### Steps to Reproduce the Issue
Load M113 or Supply/Fuel/Ammo Cargo Boxes into a CH53, CH47 or C130j
Fly around with bad ping.

### Screenshots, Serverlog or any other helpful Information
N/A

**Comment by uaon** [comment]
TODO:
Look into disabling collisions via "simulation" on load of vehicle obj.

**Comment by Elemtael** [comment]
Closing due to aging.
