### ISSUE TITLE
A-10C FIR weapons don't appear to support ACE loading properly

### ISSUE THREAD

**Issue by SyniRon** [7Cav/Liberation#13]
Loading SniperXR pod and AGM Maverick 65H missles as example

Weapons appear to load correctly using configure pylons ace option, however, once loaded they are not selectable as pilot of the aircraft.

Loaded instead using AWS menu from FIR the weapons work as expected.

Also something else appears to act as a FIRAWS station as the menu was still usable at FOB ALPHA

**Comment by uaon** [comment]
Appears to be hardcoded into the mod, no option to disable pods on AWS menu
