### ISSUE TITLE
Cannot pull multiple items of the same type from arsenal

### ISSUE THREAD

**Issue by SyniRon** [7Cav/Liberation#15]
Get Vector21 nite from arsenal, leave arsenal and put vector in backpack
Reenter arsenal get mx-2a, leave arsenal and receive message "following items not allowed: Vector_ace" and have item removed from backpack

Do the same with a weapon and receive the same message

**Comment by uaon** [comment]
@peakzero 
I'll need the arsenal classnames for the items that are getting blacklisted, there is a specific array for stopping that issue but it needs the items.

KP_liberation_config.sqf >
`KP_liberation_allowed_items_extension = [
    "ACE_Chemlight_Shield_Blue",
    "ACE_Chemlight_Shield_Green",
    "ACE_Chemlight_Shield_Orange",
    "ACE_Chemlight_Shield_Red",
    "ACE_Chemlight_Shield_White",
    "ACE_Chemlight_Shield_Yellow",
    "ACE_launch_NLAW_Used_F",
    "ACE_PreloadedMissileDummy_CUP",
    "ACE_PreloadedMissileDummy_Igla_CUP",
    "ACE_PreloadedMissileDummy_M72A6_CUP",
    "ACE_PreloadedMissileDummy_NLAW_CUP",
    "ACE_PreloadedMissileDummy_RPG18_CUP",
    "ACE_PreloadedMissileDummy_Stinger_CUP",
    "ACE_PreloadedMissileDummy_Strela_2_CUP",
    ... ...`

**Comment by uaon** [comment]
Adding to v0.96.7a-7Cav-0.2 milestone
